### ISSUE TITLE
FileNotFound Exception when clicking on pawn

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [remmintan/minefortress#12]
**Describe the bug**
Error (warning) while loading texture

**To Reproduce**
Steps or conditions to reproduce the behavior:
Just click on the pawn

**Screenshots**
```
[19:02:00] [Render thread/WARN]: Failed to load texture: minecraft:hud/hotbar
java.io.FileNotFoundException: minecraft:hud/hotbar
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_4625(class_1049.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:118) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem._setShaderTexture(RenderSystem.java:1232) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.setShaderTexture(RenderSystem.java:1225) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_25295(class_332.java:442) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_25297(class_332.java:433) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_25291(class_332.java:405) ~[client-intermediary.jar:?]
	at org.minefortress.renderer.gui.hud.SelectedColonistHudLayer.renderIcon(SelectedColonistHudLayer.java:68) ~[minefortress-1.11.1-beta.jar:?]
	at org.minefortress.renderer.gui.hud.SelectedColonistHudLayer.renderHud(SelectedColonistHudLayer.java:40) ~[minefortress-1.11.1-beta.jar:?]
	at org.minefortress.renderer.gui.hud.AbstractHudLayer.render(AbstractHudLayer.java:64) ~[minefortress-1.11.1-beta.jar:?]
	at org.minefortress.renderer.gui.hud.FortressHud.render(FortressHud.java:68) ~[minefortress-1.11.1-beta.jar:?]
	at net.minecraft.class_329.handler$zoi001$minefortress$render(class_329.java:2474) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:399) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:927) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[minecraft-1.20.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```

**Environment info:**
 - OS: Windows 10 Pro (22H2 19045)
 - Minecraft version: 1.20.2
 - Mod Version 1.11.1-beta

**Any other mods that you use**
modmenu-8.0.1
sodium-fabric-mc1.20.2-0.5.5
fabric-api-0.91.5+1.20.2

**Comment by remmintan** [comment]
I managed to fix it with the 12.0.0 beta release. Will check one more time in the evening and close the issue
